### Requisição 1 - Listar todas as escolas
GET http://localhost:3000/escolas
Content-Type: application/json

###

### Requisição 2 - Cadastrar uma nova escola
POST http://localhost:3000/escolas
Content-Type: application/json

{
  "nome": "uniersidade padre anchieta",
  "endereco": "Rua das Flores, 123 - Centro"
}

###

### Requisição 3 - Cadastrar outra escola
POST http://localhost:3000/escolas
Content-Type: application/json

{
  "nome": "Colégio modelo",
  "endereco": "Av. Brasil, 456 - Bairro Novo"
}
